home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('result/', views.post, name='result'),
    path('mesh/<int:json_no>/', views.othermeshquery, name='meshresult'),
    path('mesh/<int:json_no>/<int:abs_index>/' , views.paginate, name='paginate'),
    path('paperdetail/<int:json_no>/<int:currindex><int:offset>/' , views.paperdetail, name='paperdetail'),
    path('seesimilar/<int:json_no>/<int:currindex><int:offset>/' , views.seesimilar, name='seesimilar'),
    path('genecloud/<int:json_no>/', views.genecloud, name='genecloud'),
    path('genefile/<int:json_no>/', views.genefile, name='genefile'),
    path('meshcloud/<int:json_no>/', views.meshcloud, name='meshcloud'),
    path('entityrelation/<int:json_no>/<int:option>/', views.entityrelation, name='entityrelation'),
    path('entities/<int:json_no>/<int:eoption>/', views.entities, name='entities'),
    path('user-feedback/', views.feedback, name='feedback'),
    path('rerank/', views.rerank, name='rerank'),
    path('entity-feedback/', views.entity_feedback, name='entity-feedback'),

]

searchtool/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
	path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from . import goldencorpus
from . import mesh_explosion
from . import clusterer
from . import postprocessing
from . import mesh_explosion
from . import biological_model
from . import entity_recognition as enrecog
from . import relation_data_prepare as relation
from collections import Counter, OrderedDict
from stop_words import get_stop_words  # use as : list(get_stop_words('en'))
from nltk.corpus import stopwords      # use as : list(stopwords.words('english'))
import scispacy,spacy
import nltk
import json
import re
import operator
import pickle
import tqdm
import numpy as np

best_mesh_terms_id = OrderedDict()
best_mesh_terms = OrderedDict()
tags = []
query = None
gene_filepath = None
pmid_filepath = None
gene_set = []
stop_words = []
mesh_terms = []

def index(request):
	return render(request,'home/index.html')

# called when user enters query and gene set 
# It is a post request
def post(request,isfeedback = None,feedobj = None):
	# if gene given it constructs golden corpus 
	# if pmids given , it is used as golden corpus
	# then computes all combination of queries by calling mesh explosion file
	# finally cluster all queries and return information of best query
	# for best query corresponding json is opened and context object is made 
	# some variables are made global so that other functions can use last instance value of the variables
	global best_mesh_terms
	global best_mesh_terms_id
	global query
	global gene_filepath
	global pmid_filepath
	global gene_set
	global cluster_algo
	global tags
	global mesh_terms

	# local variables
	representative_id = 0
	representative = None
	corpuslen = 10000


	if request.method == 'POST':
		# if it is a call from feedback function
		if isfeedback :
			print("feedback")
			query = feedobj['query']
			gene_filepath = feedobj['gene_filepath']
			pmid_filepath = feedobj['pmid_filepath']
			gene_set = feedobj['gene_set']
			cluster_algo = feedobj['cluster_algo'] # not using
		else:
			print("non feedback")
			query = request.POST.get('query',None)
			gene_filepath = request.POST.get('genefile',None)
			pmid_filepath = request.POST.get('pmidfile',None)
			gene_set = request.POST.get('geneset',None)
			cluster_algo = request.POST.get('cluster',None) # not using 
		if query:
			if gene_filepath or gene_set:
				# create golden corpus
				corpus = goldencorpus.GoldenCorpus()
				found,mesh_terms = corpus.fetchData(query,corpuslen)
				if not found:
					return render(request,'home/error.html',{"message":"Error in fetching data"})
				else:
					rel_docs = corpus.get_rel_docs_pmid(query,gene_filepath,gene_set)
					# return HttpResponse("testing")
			else:
				# Golden corpus already given
				if pmid_filepath:
					path = "home/"+pmid_filepath
					with open(path,"r") as fp:
						rel_docs = fp.read().split('\n')
					# print(rel_docs)
					if len(rel_docs) < 20:
						return render(request,'home/error.html',{"message":"Please give atleast 20 PMIDs"})
				else:
					return render(request,'home/error.html',{"message":"Neither gene set nor pmids given"})
			if len(mesh_terms) > 0:
				# construct all combination of queries and for each query retrieve top k documents
				# top k documents are stored in json files in data_folder
				mesh_exp = mesh_explosion.DataForEachMeshTerm(mesh_terms,query)
				path = mesh_exp.get_data_foldername(query)
				# default call k-Means algo with k = 5
				clus = clusterer.Clusterer(rel_docs,path,True,5)

				# You can add new clustering algo here
				# if cluster_algo == None or int(cluster_algo) == "1":
				# 	print("kmean")
				# else:
				# 	print("dbscan")
				# 	clus = clusterer.Clusterer(rel_docs,path,False,5)

				# Keeping globaly to get access from other functions
				# representative_id is best json no
				# representative is best query 
				#  best_mesh_terms_id is dictionary of cluster no and corresponding array of json numbers in that cluster
				representative_id,representative, best_mesh_terms_id, best_mesh_terms = clus.cluster()
			else:
				return render(request,'home/error.html',{"message":"No meshterms received from pubmed"})
			if representative:
				# get all information from representative json
				# then make a context object and send to template as argument
				pp = postprocessing.PostProcessing()
				trimmedtitles , trimmedabs, completeabs = pp.getTitleAbs(0,representative_id,query) 
				topdocs = zip(trimmedtitles, trimmedabs)
				# topmesh contains zipped value of best queries and their json number 
				topmesh = OrderedDict()
				for clus_no,json_arr in best_mesh_terms.items():
					topmesh[clus_no] = zip(json_arr,best_mesh_terms_id[clus_no])

				previndex = -10
				nextindex = 10
				currindex = 0
				context = {
					'query' : query,
					'topdocs' : topdocs,
					'topmesh' : topmesh,
					'currindex' : currindex,
					'previndex' : previndex,
					'nextindex' : nextindex,
					'json_no' : representative_id,
				}
				return render(request,'home/detail.html',context)
			else:
				return render(request,'home/error.html',{"message":"No result found!!"})
		else:
			return render(request,'home/error.html',{"message":"No query found in post request!!"})
	else:
		return render(request,'home/error.html',{"message":"Not a post request!!"})


# used when user clicks other search queries 
def othermeshquery(request, json_no):
	# open json_no file and get title, abstracts
	# this is done in post processing file
	# also get other mesh information 
	global best_mesh_terms
	global best_mesh_terms_id
	global tags
	global query

	if request.method == 'GET':

		pp = postprocessing.PostProcessing()
		# tags = pp.term_tagging(mesh)

		# zip is used to simplify accessing data in templates [need single for loop]
		trimmedtitles , trimmedabs, completeabs = pp.getTitleAbs(0,json_no,query) 
		topdocs = zip(trimmedtitles, trimmedabs)
		
		topmesh = OrderedDict()
		for clus_no,json_arr in best_mesh_terms.items():
			topmesh[clus_no] = zip(json_arr,best_mesh_terms_id[clus_no])
		# start with index 0 from selected json [which contain clicked query]
		previndex = -10
		nextindex = 10
		currindex = 0
		context = {
			'query' : query,
			'topdocs' : topdocs,
			'topmesh' : topmesh,
			'currindex' : currindex,
			'previndex' : previndex,
			'nextindex' : nextindex,
			'json_no' : json_no,
		}
		return render(request,'home/detail.html',context)

# when user click next and previous button we show next 10 or previous 10 documents from corresponding json file
def paginate(request, json_no, abs_index):
	# similar to othermeshquery function but with proper index
	global best_mesh_terms
	global best_mesh_terms_id
	global tags
	global query

	pp = postprocessing.PostProcessing()
	trimmedtitles , trimmedabs, completeabs = pp.getTitleAbs(abs_index,json_no,query) 
	topdocs = zip(trimmedtitles, trimmedabs)
	
	topmesh = OrderedDict()
	for clus_no,json_arr in best_mesh_terms.items():
		topmesh[clus_no] = zip(json_arr,best_mesh_terms_id[clus_no])

	previndex = abs_index - 10
	nextindex = abs_index + 10	
	currindex = abs_index
	context = {
		'query' : query,
		'topdocs' : topdocs,
		'topmesh' : topmesh,
		'currindex' : currindex,
		'previndex' : previndex,
		'nextindex' : nextindex,
		'json_no': json_no,
	}
	return render(request,'home/detail.html',context)

# get all the json number of the cluster which contains json_no 
# used in gene cloud, entityrelation , entities etc functions
def cluster_by_jsonno(json_no):
	global best_mesh_terms_id
	json_arr = []
	for k,v in best_mesh_terms_id.items():
		for jno in v:
			if json_no == jno:
				json_arr = v
				break
	return json_arr

def genefile(request, json_no):
	global query
	global gene_filepath

	json_arr = cluster_by_jsonno(json_no)
	pp = postprocessing.PostProcessing()
	data = pp.gene_file(query, json_arr)
	response = HttpResponse("\n".join(data),content_type="application/text")
	response["Content-Disposition"] = "attachment; filename=genefile.txt"
	return response
	# return HttpResponse("\n".join(data))
	

# gene cloud is constructed for an entire cluster
def genecloud(request, json_no):
	global query
	global gene_filepath

	json_arr = cluster_by_jsonno(json_no)
	pp = postprocessing.PostProcessing()
	flag,data = pp.gene_cloud(query,json_arr)
	if flag:
		return render(request, 'home/genecloud.html',{'data': data})
	else:
		return render(request,'home/error.html',{"message":"Something wrong : check postprocessing.py"})

# For now it constructs for a single json 
# But you can do it for current cluster just like gene cloud
def meshcloud(request, json_no):
	global query
	pp = postprocessing.PostProcessing()
	flag,meshobj = pp.mesh_cloud(json_no,query)
	if flag:
		return render(request, 'home/meshcloud.html', {'meshobj': meshobj})
	else:
		return HttpResponse("Something wrong with mesh cloud!")
# showing entity relation in a cluster . Relation between protein-protein, gene-protein and disease-protein
def entityrelation(request, json_no, option):
	global query

	json_arr = cluster_by_jsonno(json_no)
	pp = postprocessing.PostProcessing()
	flag,data = pp.entityrelation(query,json_arr)
	if flag:
		return render(request,'home/multirelation.html',{"data": data})
	else:
		return render(request,'home/error.html',{"message":"Something wrong with entity relation"})
# To show all entities of the selected cluster
def entities(request,json_no,eoption):
	global query

	print("json_no: ", json_no)
	print("option: ", eoption)
	json_arr = cluster_by_jsonno(json_no)
	print("arr: ",json_arr)
	pp = postprocessing.PostProcessing()
	flag,allentities,data = pp.get_entities(query,json_arr,eoption)
	if flag:
		return render(request,'home/entities.html',{'entities': allentities,'data':data})
	else:
		return HttpResponse("No entities")
# when user clicks a title this is invoked
def paperdetail(request,json_no,currindex,offset):
	# open json
	global query


	abstracts = []
	titles = []
	mesh_terms = []
	pmids = []
	# get data folder path

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Result for {{query}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'home/detail.css' %}" />
    <!-- <script src="main.js"></script> -->
</head>
<body>
    <div class="container">
        <div class="top-container">
            <div class="form-container">
                <form action="{% url 'home:result' %}" method="post" id="form">
                    {% csrf_token %}
                    <div class="search-container">
                        <input id="search-field" type="text" name="query">
                        <!-- <button id="submit-field" type="submit">Search</button> -->
                    </div>	
                    <div class="select-file">
                        <label for="avatar">Choose a gene file:</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                    </div>
                </form>
            </div>
        </div>
        <div class="leftright-container">
            <div class="left-container">
                {% if topdocs %}
                {% for title , abs in topdocs %}
                <div class="titleabs">
                    <h2><a>{{title}}</a></h2>
                    <span class="abs">{{abs}}</span>
                </div>
                {% endfor %} 
                {% endif %}
            </div>
            <div class="middle-container">
                
            </div>
            <div class="right-container">
                <div>
                    <h1>Other possible search queries</h1>
                </div>
                <div class="meshterms">
                    {% if mesharr %}
                        {% for zipmesh in mesharr %}
                            {% for mesh, meshid in zipmesh %}
                                <li class="meshterm">
                                    <a href="{% url 'home:meshresult' meshid %}" class="meshlink">{{mesh}}</a>
                                </li>
                            {% endfor %}
                        {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="pagination">
            
        </div>
    </div>
</body>
<footer class="footer-container">

</footer>
</html>

home/templates/home/error.html
<html>
    {% if message %}
        <p>{{message}}</p>
    {% endif %}
</html>

home/templates/home/genecloud.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{title}}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'home/genecloud.css' %}" />
        <script src="//d3js.org/d3.v4.js"></script>
    </head>
    <body>
        <!-- The Modal which is hidden initially -->
        <div id="myModal" class="modal">
            <div id="modal-container" class="modal-content">
                <span class="close">&times;</span>
                <div id="content"></div>
            </div>
        </div>
        <div>
            {% if data %}
                <div id="gene-chart" style="width: 100%; height:100%"></div>
                {{ data|json_script:"mydata" }}
            {% else %}
                {% if message %}
                    {{ message }}
                {% endif %}
            {% endif %}
        </div>
        <script>
            // main d3 logic
            let rootdata = JSON.parse(document.getElementById('mydata').textContent);
            console.log(rootdata)
            let width = window.screen.width;
            let height = window.screen.height;
            const diameter = 960,
                format = d3.format(",d"),
                color = d3.scaleOrdinal(d3.schemeCategory20c);
            // bubble layout
            const bubble = d3.pack()
                .size([diameter, diameter])
                .padding(1.5);

            const svg = d3.select("#gene-chart").append("svg")
                .attr("width", diameter)
                .attr("height", diameter)
                .attr("class", "bubble")
                .attr("transform","translate(100,50)");
           
            const root = d3.hierarchy(rootdata)
                .sum(function(d) { return d.value; })
                .sort(function(a, b) { return b.value - a.value; });

            bubble(root);
            const node = svg.selectAll(".node")
                .data(root.children)
                .enter().append("g")
                .attr("class", "node")
                .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; })

            node.append("title")
                .text(function(d) { return d.data.name; });

            node.append("circle")
                .attr("r", function(d) { return d.r > 2 ? d.r : 0; })
                .style("fill", function(d) { 
                    return color(Math.floor(Math.random()*20) + 0); 
                })

            node.append("text")
                .attr("dy", ".3em")
                .style("text-anchor", "middle")
                .text(function(d) { return d.r > 2 ? d.data.name.substring(0, d.r / 3) : ""; });

            node.on("click",(d)=> {
                console.log("clicked: " + d.data.name)
                // First create the div element since on close we will remove it
                let container = document.getElementById('modal-container');
                let modaldiv = document.createElement("div");
                modaldiv.setAttribute("id","content");
                container.appendChild(modaldiv);
                // Get the modal
                let modal = document.getElementById('myModal');
                let modalcontent = document.getElementById('content');
                if(d.data.title.length){
                    for(_i = 0; _i < d.data.title.length; _i++){
                        let mydiv = document.createElement("div");
                        let title = document.createElement("h2");
                        title.style.color = "#191983";
                        title.style.fontFamily = "'Segoe UI',Arial,Helvetica,Sans-Serif";
                        title.style.fontSize = "1.2em";
                        let titletext = document.createTextNode(d.data.title[_i]);
                        let pmid = document.createElement("h3");
                        pmid.style.color = "pink";
                        pmid.style.fontSize = "1.0em";
                        pmid.style.fontFamily = "'Segoe UI',Arial,Helvetica,Sans-Serif";
                        let pmidtext = document.createTextNode("PMID: " + d.data.pmids[_i]);
                        title.appendChild(titletext);
                        pmid.appendChild(pmidtext);
                        mydiv.appendChild(title);
                        mydiv.appendChild(pmid);
                        modalcontent.appendChild(mydiv);
                        // console.log(modalcontent);
                    }
                }
                else{
                    let title = document.createElement("h2");
                    let titletext = document.createTextNode("This gene is not present in any paper.");
                    title.appendChild(titletext);
                    modalcontent.appendChild(title);
                }
                modal.style.display = "block";

                // Get the <span> element that closes the modal
                let span = document.getElementsByClassName("close")[0];

                // When the user clicks on <span> (x), close the modal
                span.onclick = function() {
                    modal.style.display = "none";
                    modalcontent.remove();
                }
                // When the user clicks anywhere outside of the modal, close it
                window.onclick = function(event) {
                    if (event.target == modal) {
                        modal.style.display = "none";
                    }
                } 
            });

        </script>
    </body> 
</html>

home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Welcome to - MEDLINE Search</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'home/index.css' %}" />
        <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>  
        <script>
            $(document).ready(function(){
                console.log("clicked");
                $("input[name$='same']").click(function(){
                    let val = $(this).val();
                    $("div.select-file").hide();
                    $("#option" + val).show();
                    let id = "option"+val;
                    if(id == "option1"){
                        $('#pmid').val('');
                        $('#gene-name-area').val('');
                    }
                    else if(id == "option2"){
                        $('#gene').val('');
                        $('#gene-name-area').val('');
                    }
                    else if(id == "option3"){
                        $('#gene').val('');
                        $('#pmid').val('');
                    }
                });
            });
        </script>
</head>
<body>
    <div class="form-container">
        <form action="{% url 'home:result' %}" method="post" id="form">
            {% csrf_token %}
            <div class="search-container">
                <input id="search-field" type="text" name="query" id="InputID">
                <!-- <button id="submit-field" type="submit">Search</button> -->
            </div>	
            <div style="display: flex">
                <!-- Radio buttons -->
                <div><input type="radio" name="same" value="1"> Gene file</div><br>
                <div><input type="radio" name="same" value="2"> PMID file</div><br>
                <div><input type="radio" name="same" value="3"> Gene names</div>
                <div style="background-color: pink"><input type="radio" name="cluster" value="1"> K-Means </div><br>
                <div style="background-color: pink"><input type="radio" name="cluster" value="2"> DBSCAN</div>
            </div>
            <div id="option1" class="select-file">
                <!-- Gene file selection -->
                <label for="gene" id="filelabel">Choose a gene file:</label>
                &nbsp;&nbsp;&nbsp;
                <input type="file" id="gene" name="genefile" accept="text">
            </div>	
            <div id="option2" class="select-file">
                <!-- PMID file selection -->
                <label for="pmid" id="filelabel">Choose a PMID file:</label>
                &nbsp;&nbsp;&nbsp;
                <input type="file" id="pmid" name="pmidfile" accept="text">
            </div>
            <div id="option3" class="select-file">
                <!-- Enter gene names -->
                <textarea name="geneset" id="gene-name-area" cols="30" rows="10" style="width: 100%; height: 50px"></textarea>
            </div>
        </form>
    </div>  
</body>
</html>

home/templates/home/meshcloud.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{title}}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'home/meshcloud.css' %}" />
        <script src="https://d3js.org/d3.v4.min.js"></script>
    </head>
    <body>
        <div>
            {% if meshobj %}
                <div id="mesh-chart"></div>
                {{ meshobj|json_script:"mydata" }}
            {% endif %}
        </div>
        <script>
            // main d3 logic
            let rootdata = JSON.parse(document.getElementById('mydata').textContent);
            console.log(rootdata)
            let width = window.screen.width;
            let height = window.screen.height;
            const diameter = 960,
                format = d3.format(",d"),
                color = d3.scaleOrdinal(d3.schemeCategory20c);

            const bubble = d3.pack()
                .size([diameter, diameter])
                .padding(1.5);

            const svg = d3.select("#mesh-chart").append("svg")
                .attr("width", diameter)
                .attr("height", diameter)
                .attr("class", "bubble")
                .attr("transform","translate(100,50)");
           
            const root = d3.hierarchy(rootdata)
                .sum(function(d) { return d.value; })
                .sort(function(a, b) { return b.value - a.value; });

            bubble(root);
            const node = svg.selectAll(".node")
                .data(root.children)
                .enter().append("g")
                .attr("class", "node")
                .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; })

            node.append("title")
                .text(function(d) { return d.data.name;});

            node.append("circle")
                .attr("r", function(d) { return d.r; })
                .style("fill", function(d) { 
                    return color(Math.floor(Math.random()*20) + 0); 
                })

            node.append("text")
                .attr("dy", ".3em")
                .style("text-anchor", "middle")
                .text(function(d) { return d.r > 20 ?  d.data.name.substring(0, d.r / 5) : " "; });

            node.on("click",(d)=> {

            });

        </script>
    </body>
</html>

home/templates/home/psudodetail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Result for {{query}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'home/detail.css' %}" />
</head>
<body>
    <div class="container">
        <div class="top-container">
            <div class="form-container">
                <form action="{% url 'home:result' %}" method="post" id="form">
                    {% csrf_token %}
                    <div class="search-container">
                        <input id="search-field" type="text" name="query">
                    </div>	
                    <div class="select-file">
                        <label for="avatar" id="filelabel">Choose a gene file:</label>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="file" id="avatar" name="avatar" accept="text">
                    </div>
                </form>
            </div>
        </div>
        <div class="leftright-container">
            <div class="left-container">
                {% if topdocs %}
                    {% for title , abs in topdocs %}
                    <div class="titleabs">
                        <h2><a href="{% url 'home:paperdetail' json_no currindex forloop.counter0 %}">{{title}}</a></h2>
                        <span class="abs">{{abs}}</span>
                    </div>
                    {% endfor %} 
                {% endif %}
            </div>
            <div class="middle-container">
                <div>
                    <h2>Visualize related genes and relation among them</h2>
                </div>
                <div class="cloud">
                    <span><a href="{% url 'home:genecloud' json_no %}">Gene Cloud </a></span>
                    <span><a href="{% url 'home:generelation' json_no %}">Gene Relation</a></span>
                    <span><a href="{% url 'home:meshcloud' json_no %}">Mesh Cloud</a></span>
                </div>
            </div>
            <div class="right-container">
                <div>
                    <h2>Other specific search queries</h2>
                </div>
                <div class="meshterms">
                    {% if mesharr %}
                        {% for zipmesh in mesharr %}
                            {% for mesh, meshid in zipmesh %}
                                <li class="meshterm">
                                    <a href="{% url 'home:meshresult' meshid %}" class="meshlink">{{mesh}}</a>
                                </li>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="pagination">
            <div>
                {% if previndex >= 0 %}
                    <a href="{% url 'home:paginate' json_no previndex %}" class="paginate-button">Prev</a>
                {% endif %}
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{% url 'home:paginate' json_no nextindex %}" class="paginate-button">Next</a>
            </div>
            
        </div>
    </div>
</body>
<footer class="footer-container">

</footer>
</html>

home/templates/home/test.html
<style>
    .search-container {
        position: relative;
        margin: 0 auto;
        margin-left: 150px;
        width: 632px;
    }
    .search-div {
        background: #fff;
        display: flex;
        border-radius: 8px;
        border: 1px solid #dfe1e5;
        box-shadow: none;
        height: 39px;
        width: 630px;
        border-radius: 24px;
        z-index: 3;
        height: 44px;
        margin: 0 auto;
    }

    .SDkEP {
        flex: 1;
        display: flex;
        padding: 5px 4px 0 16px;
        padding-left: 20px;
    }
    .a4bIc {
        display: flex;
        flex: 1;
        flex-wrap: wrap;
    }
    .vdLsw {
        color: transparent;
        flex: 100%;
        white-space: pre;
    }
    .gsfi {
        font: 16px arial,sans-serif;
        line-height: 34px;
        height: 34px !important;
    }
    .gLFyf {
        background-color: transparent;
        border: none;
        margin: 0;
        padding: 0;
        color: rgba(0,0,0,.87);
        word-wrap: break-word;
        outline: none;
        display: flex;
        flex: 100%;
        -webkit-tap-highlight-color: transparent;
        margin-top: -37px;
    }
    
    .Tg7LZd {
        border-radius: 0;
        -webkit-border-top-right-radius: 8px;
        height: 44px;
        width: 44px;
        background: transparent;
        border: none;
        cursor: pointer;
        flex: 0 0 auto;
        padding: 0;
    }
    .rINcab {
        background: none;
        color: #4285f4;
        height: 24px;
        width: 24px;
        margin: auto;
    }
    .z1asCe, .qa__svg-icon {
        display: inline-block;
        fill: currentColor;
        height: 24px;
        line-height: 24px;
        position: relative;
        width: 24px;
    }
</style>
<div class="search-container">
    <div class="search-div">
        <div class="SDkEP">
            <div class="a4bIc">
                <div class="vdLsw gsfi"></div>
                <input class="gLFyf gsfi" maxlength="2048" name="q" type="text" role="combobox" spellcheck="false" title="Search" placeholder="Enter query here " aria-label="Search">
            </div>
        </div>  
        <button class="Tg7LZd" label="Google Search" type="button">
            <div class="rINcab"> 
                <span class="z1asCe MZy1Rb">
                    <svg focusable="false" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                        <path d="M15.5 14h-.79l-.28-.27A6.471 6.471 0 0 0 16 9.5 6.5 6.5 0 1 0 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
                    </svg>
                </span> 
            </div> 
        </button> 
    </div>
</div>